#ifndef COMMAND_H
#define COMMAND_H

enum OMNIWHEEL_ALCOMMAND
{
    OMNIWHEEL_AL_NO_ACT = 100,
    OMNIWHEEL_AL_GOTODES,
    OMNIWHEEL_AL_VELMODE,
    OMNIWHEEL_AL_CHANGEPOS,
    OMNIWHEEL_AL_CONTROL,
    OMNIWHEEL_AL_MANUAL,
    OMNIWHEEL_AL_RADIUS,
    OMNIWHEEL_AL_ROS
};
enum WALKREADYCOMMAND
{
    WALKREADY_NO_ACT = 100,
    WALKREADY_GO_WALKREADYPOS,
    WALKREADY_GO_HOMEPOS,
    WALKREADY_WHEELCMD
};

enum ROBOTWORLD_ALCOMMAND
{
    ROBOTWORLD_AL_NO_ACT = 100,
    ROBOTWORLD_AL_OMNIWHEEL_MOVE,
    ROBOTWORLD_AL_JOYSTICK_MOVE,
    ROBOTWORLD_AL_SAVE,
    ROBOTWORLD_AL_GRASPING,
    ROBOTWORLD_AL_HAND_GO,
    ROBOTWORLD_AL_VISION_GRASP,
    ROBOTWORLD_AL_OMNIMOVE,
    ROBOTWORLD_AL_RESET,
    ROBOTWORLD_AL_TEST
};

#endif // COMMAND_H
